version: '3.8'

services:
  go:
    container_name: "go-lotto"
    build:
      context: .
      dockerfile: Docker/Go/Dockerfile
    volumes:
      - ./src:/home
  database:
    image: "mongo"
    container_name: "mongo-lotto"
    environment:
      - MONGO_INITDB_DATABASE=lotto-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./Docker/Mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./Docker/Mongo/db:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"